### ISSUE TITLE
Error in conversion

### ISSUE THREAD

**Issue by dugwood** [Fylax/forceutf8#3]
Thanks for the port to composer.

You've forked from a repository that introduced an issue after forking from the original repository. So you've got the bug too :-) 

I'm trying to fix `MAÃÂL`, which is converted to `MAÃ?Â?L` with your library, but not with the original repository that translates it to `MAËL` (the expected result).

Seems to be the choice for `Windows-1252` instead of `ISO-8859-15` here: https://github.com/Fylax/forceutf8/blob/master/ForceUTF8/Encoding.php#L329

`utf8_decode()` « Converts a string from UTF-8 to ISO-8859-1 »

And the source only uses utf8_decode, so it should be ISO-8859-15 instead of Windows-1252: https://github.com/neitanod/forceutf8/blob/master/src/ForceUTF8/Encoding.php#L343

But perhaps it creates collateral damages, so I don't know if it should be fixed... As using iconv is using Windows-1252: https://github.com/neitanod/forceutf8/blob/master/src/ForceUTF8/Encoding.php#L347 

Perhaps my original string is wrong (but it exists in my database) :smile:

**Comment by Fylax** [comment]
Seems like I wasn't receiving notifications from issues, my bad for not checking earlier.
I did indeed use Windows-1252 to reflect the icov, I admit I didn't investigate enough about utf8_decode as the library with this code worked seamlessly with our production database (I see that ISO and Windows are ALMOST the same encoding, so we were probably very lucky).
Perhaps you made a mistake in your issue; correct me if  I'm wrong but the mb_convert_enconding should be ISO-8859-1 and not ISO-8859-15, right?

I am considering making a major release to address the issue (along with some merges from upstream)

**Comment by dugwood** [comment]
@Fylax ISO-8859-15 just includes the Euro sign (€) which was added after the Euro creation, to expand ISO-8859-1. It's just a new character, you may or may not use it instead of ISO-8859-1 :-)

Anyway, I was handling a lot of crap on my end, double-encoded strings and the like, and your port helped me a lot!

**Comment by Fylax** [comment]
Luckily, aligning to upstream was quite trivial so I managed to update and make the fix.
For the time being, I used ISO-8859-1 just for consistency with the rest of the code but if deemed useful I might change it all to ISO-8859-15

Out of curiosity, what PHP version are you using? I was thinking retargeting the project to PHP 8, since anything before it is out of life in any case

**Comment by dugwood** [comment]
I'm using Debian's stable package, which is currently PHP 8.2.24. Debian is often « late » on versions (tradeoff for security and stability), so if it's currently 8.2, you can clearly remove PHP 7 support.

Thanks for the fix, I'll let the ticket open, but close it when you think it's okay.

**Comment by Fylax** [comment]
Hello, I created the PR #4  for retargeting to PHP 8.1 (being the last supported one).
For the time being I kept it backward compatible, hence I couldn't define some types in parameters and returns.

Would you mind giving a quick look? (better safe than sorry)

Thank you

**Comment by dugwood** [comment]
I’ll be out for a few days, I’ll test it on Tuesday if that’s fine by you.

**Comment by Fylax** [comment]
Sure, no rush.
You waited long enough for this PR!

**Comment by dugwood** [comment]
Hello @Fylax 

I've just been able to test it again. Works as expected! I've removed the patch I've made: I was passing the encoding as a parameter to `Encoding::fixUTF8` and `Encoding::utf8_decode`.

Thanks for your work!
